version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080

  auth:
    image: quay.io/openware/authz-dummy:0.1.1
    ports:
      - "8005:8005"
    environment:
      DUMMY_USER_EMAIL: "demo@zsmart.tech"
      DUMMY_USER_UID: "IDB5B29F5B92"
      DUMMY_USER_ROLE: "admin"
      DUMMY_USER_LEVEL: 3
      DUMMY_USER_STATE: "active"
      DUMMY_JWT_PRIVKEY_FILE: "/secrets/rsa-key"
      DUMMY_JWT_TTL: 86400
    volumes:
      - ./secrets:/secrets:ro

  gateway:
    image: quay.io/datawire/ambassador:0.53.1
    ports:
      - "8080:80"
    depends_on:
      - auth
    volumes:
      - ./gateway:/ambassador/ambassador-config/:ro
    entrypoint:
      - sh
      - -exc
      - |
        # Allow accessing host's 0.0.0.0 so we can connect to a local finex
        # from the gateway container
        ip -4 route list match 0/0 | awk '{print $$3" finex-api"}' >> /etc/hosts
        # Continue with the default entrypoint
        ./entrypoint.sh
