name: Golang Build and Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go build -o quantex-api ./cmd/quantex-api/main.go
        go build -o quantex-engine ./cmd/quantex-engine/main.go
        go build -o quantex-migrator ./cmd/quantex-migrator/main.go
    - name: Test
      run: go test -v ./...
